[theme]
primaryColor = "#008c95"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f3f6fa"
textColor = "#10243a"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
address = "127.0.0.1"
